# Generated by Django 3.0.4 on 2020-09-09 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetentry',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='aggregatebudget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('purse.budgetcategory',),
        ),
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Надкатегория',
                'verbose_name_plural': 'Надкатегории',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('purse.budgetcategory',),
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purse.SubCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='super_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='purse.SuperCategory'),
        ),
    ]
