# Generated by Django 3.0.4 on 2020-09-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0002_auto_20200910_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatebudget',
            name='expenses_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма расхода'),
        ),
        migrations.AlterField(
            model_name='aggregatebudget',
            name='income_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма дохода'),
        ),
    ]
